[build.env]
passthrough = [
    "CFG_COMMIT_HASH",
    "CFG_COMMIT_DATE",
]
[build]
pre-build = [                                  # additional commands to run prior to building the package
    "mkdir -vp ${CARGO_HOME:-$HOME/.cargo}",

"""
cat << EOF | tee -a ${CARGO_HOME:-$HOME/.cargo}/config.toml
[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[registries.mirror]
index = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"
EOF
"""
]

[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install -y unzip",
    "PB_REL=\"https://github.com/protocolbuffers/protobuf/releases\";curl -LO $PB_REL/download/v28.2/protoc-28.2-linux-x86_64.zip",
    "unzip protoc-28.2-linux-x86_64.zip -d /opt/.local",
    "export PATH=\"$PATH:/opt/.local/bin\";chmod +x /opt/.local/bin/protoc",
    "protoc --version;export PROTOC=/opt/.local/bin/protoc",
]
[target.x86_64-unknown-linux-musl.env]
passthrough = ["PROTOC=/opt/.local/bin/protoc"]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get install -y unzip clang",
    "PB_REL=\"https://github.com/protocolbuffers/protobuf/releases\";curl -LO $PB_REL/download/v28.2/protoc-28.2-linux-x86_64.zip",
    "unzip protoc-28.2-linux-x86_64.zip -d /opt/.local",
    "export PATH=\"$PATH:/opt/.local/bin\";chmod +x /opt/.local/bin/protoc",
    "protoc --version;export PROTOC=/opt/.local/bin/protoc",
]
[target.aarch64-unknown-linux-musl.env]
passthrough = ["PROTOC=/opt/.local/bin/protoc"]

[target.x86_64-pc-windows-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y unzip clang",
    "PB_REL=\"https://github.com/protocolbuffers/protobuf/releases\";curl -LO $PB_REL/download/v28.2/protoc-28.2-linux-x86_64.zip",
    "unzip protoc-28.2-linux-x86_64.zip -d /opt/.local",
    "export PATH=\"$PATH:/opt/.local/bin\";chmod +x /opt/.local/bin/protoc",
    "protoc --version;export PROTOC=/opt/.local/bin/protoc",
]
[target.x86_64-pc-windows-gnu.env]
passthrough = ["PROTOC=/opt/.local/bin/protoc"]
