sed -i 's/	repeated string dns_servers = 12;/	repeated string dns_servers = 12;\n	string up = 13;\n	string down = 14;/g' leaf/src/config/internal/config.proto
sed -i 's/    pub dns_servers: Option<Vec<String>>,/    pub dns_servers: Option<Vec<String>>,\n    pub up: Option<String>,\n    pub down: Option<String>,/g' leaf/src/config/common.rs
sed -i 's/    pub mtu: Option<i32>,/    pub mtu: Option<i32>,\n    pub up: Option<String>,\n    pub down: Option<String>,/g' leaf/src/config/conf/config.rs
sed -i 's/    pub tun_dns_server: Option<Vec<String>>,/    pub tun_dns_server: Option<Vec<String>>,\n    pub tun_up: Option<String>,\n    pub tun_down: Option<String>,/g' leaf/src/config/conf/config.rs
sed -i 's/"tun-dns-server" => {/"tun-up" => {\n                general.tun_up = get_string(parts[1]);\n            }\n            "tun-down" => {\n                general.tun_down = get_string(parts[1]);\n            }\n            "tun-dns-server" => {/g' leaf/src/config/conf/config.rs
sed -i 's/dns_servers: ext_general.tun_dns_server.clone(),/dns_servers: ext_general.tun_dns_server.clone(),\n                up: ext_general.tun_up.clone(),\n                down: ext_general.tun_down.clone(),/g' leaf/src/config/conf/config.rs
sed -i 's/                    let tun = Tun {/                    let tun = Tun {\n                        up: None,\n                        down: None,/g' leaf/src/config/conf/config.rs
sed -i 's/pub default_interface: Option<String>,/pub default_interface: Option<String>,\n    pub tun_up: Option<String>,\n    pub tun_down: Option<String>,/g' leaf/src/sys.rs
sed -i 's/        default_interface: Some(iface),/        default_interface: Some(iface),\n        tun_up: None,\n        tun_down: None,/g' leaf/src/sys.rs
sed -i 's/pub fn post_tun_creation_setup(net_info: &NetInfo) {/pub fn post_tun_creation_setup(net_info: \&NetInfo) {\n    if let Some(cmd) = \&net_info.tun_up {\n        tracing::info!("executing tun up command: {}", cmd);\n        let _ = std::process::Command::new("sh").arg("-c").arg(\&cmd).status();\n    }/g' leaf/src/sys.rs
sed -i 's/pub fn post_tun_completion_setup(net_info: &NetInfo) {/pub fn post_tun_completion_setup(net_info: \&NetInfo) {\n    if let Some(cmd) = \&net_info.tun_down {\n        tracing::info!("executing tun down command: {}", cmd);\n        let _ = std::process::Command::new("sh").arg("-c").arg(\&cmd).status();\n    }/g' leaf/src/sys.rs
sed -i 's/    pub fn tun_auto(&self) -> bool {/\n    #[cfg(feature = "inbound-tun")]\n    pub fn tun_up(\&self) -> Option<String> {\n        if let Some(listener) = \&self.tun_listener {\n            if let Ok(settings) = crate::config::TunInboundSettings::parse_from_bytes(\&listener.inbound.settings) {\n                return if settings.up.is_empty() { None } else { Some(settings.up) };\n            }\n        }\n        None\n    }\n\n    #[cfg(feature = "inbound-tun")]\n    pub fn tun_down(\&self) -> Option<String> {\n        if let Some(listener) = \&self.tun_listener {\n            if let Ok(settings) = crate::config::TunInboundSettings::parse_from_bytes(\&listener.inbound.settings) {\n                return if settings.down.is_empty() { None } else { Some(settings.down) };\n            }\n        }\n        None\n    }\n\n    pub fn tun_auto(\&self) -> bool {/g' leaf/src/app/inbound/manager.rs
sed -i 's/    let net_info = if inbound_manager.has_tun_listener() && inbound_manager.tun_auto() {/    #[allow(unused_mut)]\n    let mut net_info = if inbound_manager.has_tun_listener() \&\& inbound_manager.tun_auto() {/g' leaf/src/lib.rs
sed -i 's/        sys::NetInfo::default()\n    };/        sys::NetInfo::default()\n    };\n    #[cfg(all(feature = "inbound-tun", any(target_os = "macos", target_os = "linux")))]\n    {\n        net_info.tun_up = inbound_manager.tun_up();\n        net_info.tun_down = inbound_manager.tun_down();\n    }/g' leaf/src/lib.rs
